name: CI CMake

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: get
        uses: actions/checkout@v4

      - name: configure
        run: cmake -S . -B build -DBUILD_TESTS=ON
        working-directory: banking

      - name: build
        run: cmake --build build --config Release
        working-directory: banking

      - name: run tests
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ./build/Release/tests.exe
          else
            ./build/tests
          fi
        shell: bash
        working-directory: banking

      - name: generate coverage
        if: runner.os == 'Linux'
        working-directory: banking
        run: |
          pip install gcovr
          
          cd build
          
          echo "=== Генерация отчёта ==="
          gcovr \
            --root .. \
            --filter 'Account\.cpp' \
            --filter 'Transaction\.cpp' \
            --exclude '.*build.*' \
            --exclude '.*_deps.*' \
            --exclude '.*tests.*' \
            --gcov-ignore-parse-errors \
            --lcov \
            -o coverage.info \
            .
          
          echo "=== coverage.info ==="
          cat coverage.info
          
      - name: upload to coveralls
        if: runner.os == 'Linux'
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: banking/build/coverage.info
          ignore: "build/**,_deps/**,tests/**"
